#!/bin/bash
sudo apt-get install npm -y
sudo apt-get install mongodb -y
sudo apt-get install nodejs -y
sudo apt-get install mosquitto -y
sudo apt-get install unzip -y
sudo apt-get install libssl-dev -y
sudo apt-get install libc-ares-dev -y
sudo apt-get install libwebsockets-dev -y
sudo apt-get install uuid-dev xsltproc docbook-xsl -y
#wget http://www.eclipse.org/downloads/download.php?file=/mosquitto/source/mosquitto-1.4.14.tar.gz

#tar -xf "mosquitto.tar.gz"
#sudo make
#sudo make check
#sudo make install
#sudo /sbin/ldconfig
