#!/bin/bash

#wget https://nodejs.org/dist/v8.9.0/node-v8.9.0-linux-armv6l.tar.gz
#tar -xzf node-v8.9.0-linux-armv6l.tar.gz
#cd node-v8.9.0-linux-armv6l
sudo apt-get update
git clone https://github.com/AustinDidierTran/MOvIT-Detect-Frontend
echo pwd
cd ~/Desktop/MOvIT-Detect-Frontend

npm install
npm start
