#!/bin/bash

#git clone https://github.com/AustinDidierTran/MOvIT-Detect-Backend
#cd ~/Desktop/MOvIT-Detect-Backend
#sudo npm install node-red -g
#sudo npm install


node-red --userDir ~/Desktop/MOvIT-Detect-Backend --max-old-space-size=256
